//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdvancedSettings_PlaySnake {
            get {
                return ((bool)(this["AdvancedSettings_PlaySnake"]));
            }
            set {
                this["AdvancedSettings_PlaySnake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DefaultLineIndex {
            get {
                return ((int)(this["DefaultLineIndex"]));
            }
            set {
                this["DefaultLineIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All Sites")]
        public string DefaultSite {
            get {
                return ((string)(this["DefaultSite"]));
            }
            set {
                this["DefaultSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All Sectors")]
        public string DefaultBU {
            get {
                return ((string)(this["DefaultBU"]));
            }
            set {
                this["DefaultBU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool areDatesSaved {
            get {
                return ((bool)(this["areDatesSaved"]));
            }
            set {
                this["areDatesSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int defaultMappingLevel {
            get {
                return ((int)(this["defaultMappingLevel"]));
            }
            set {
                this["defaultMappingLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string maxMinCOgap {
            get {
                return ((string)(this["maxMinCOgap"]));
            }
            set {
                this["maxMinCOgap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool inControl_useRule1 {
            get {
                return ((bool)(this["inControl_useRule1"]));
            }
            set {
                this["inControl_useRule1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool inControl_useRule2 {
            get {
                return ((bool)(this["inControl_useRule2"]));
            }
            set {
                this["inControl_useRule2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool inControl_useRule3 {
            get {
                return ((bool)(this["inControl_useRule3"]));
            }
            set {
                this["inControl_useRule3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool inControl_useRule4 {
            get {
                return ((bool)(this["inControl_useRule4"]));
            }
            set {
                this["inControl_useRule4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inControl_useRule5 {
            get {
                return ((bool)(this["inControl_useRule5"]));
            }
            set {
                this["inControl_useRule5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inControl_useRule6 {
            get {
                return ((bool)(this["inControl_useRule6"]));
            }
            set {
                this["inControl_useRule6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string CSV_ExportPath {
            get {
                return ((string)(this["CSV_ExportPath"]));
            }
            set {
                this["CSV_ExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LanguageActive {
            get {
                return ((int)(this["LanguageActive"]));
            }
            set {
                this["LanguageActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool populateDTteamsFromPROD {
            get {
                return ((bool)(this["populateDTteamsFromPROD"]));
            }
            set {
                this["populateDTteamsFromPROD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double maxuptimecutoff {
            get {
                return ((double)(this["maxuptimecutoff"]));
            }
            set {
                this["maxuptimecutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool displaySAPnames {
            get {
                return ((bool)(this["displaySAPnames"]));
            }
            set {
                this["displaySAPnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AdvancedSettings_MultiConstraintAnalysisMode {
            get {
                return ((int)(this["AdvancedSettings_MultiConstraintAnalysisMode"]));
            }
            set {
                this["AdvancedSettings_MultiConstraintAnalysisMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int defaultDownTimeField {
            get {
                return ((int)(this["defaultDownTimeField"]));
            }
            set {
                this["defaultDownTimeField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedSettings_isAvailabilityMode {
            get {
                return ((bool)(this["AdvancedSettings_isAvailabilityMode"]));
            }
            set {
                this["AdvancedSettings_isAvailabilityMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int defaultDownTimeField_Secondary {
            get {
                return ((int)(this["defaultDownTimeField_Secondary"]));
            }
            set {
                this["defaultDownTimeField_Secondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WantstoSetDefaultLine {
            get {
                return ((bool)(this["WantstoSetDefaultLine"]));
            }
            set {
                this["WantstoSetDefaultLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedSettings_isTargetsEnabled {
            get {
                return ((bool)(this["AdvancedSettings_isTargetsEnabled"]));
            }
            set {
                this["AdvancedSettings_isTargetsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdvancedSettings_isPasswordCorrect {
            get {
                return ((bool)(this["AdvancedSettings_isPasswordCorrect"]));
            }
            set {
                this["AdvancedSettings_isPasswordCorrect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double Data_UptimeCutoff {
            get {
                return ((double)(this["Data_UptimeCutoff"]));
            }
            set {
                this["Data_UptimeCutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double Data_DowntimeCutoff {
            get {
                return ((double)(this["Data_DowntimeCutoff"]));
            }
            set {
                this["Data_DowntimeCutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdvancedSettings_UseNotes {
            get {
                return ((bool)(this["AdvancedSettings_UseNotes"]));
            }
            set {
                this["AdvancedSettings_UseNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedSettings_UseSimulation {
            get {
                return ((bool)(this["AdvancedSettings_UseSimulation"]));
            }
            set {
                this["AdvancedSettings_UseSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PDT_maxMinutesBetweenEvents {
            get {
                return ((double)(this["PDT_maxMinutesBetweenEvents"]));
            }
            set {
                this["PDT_maxMinutesBetweenEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string DefaultLineName {
            get {
                return ((string)(this["DefaultLineName"]));
            }
            set {
                this["DefaultLineName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GBO")]
        public string DefaultSiteAcronym {
            get {
                return ((string)(this["DefaultSiteAcronym"]));
            }
            set {
                this["DefaultSiteAcronym"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Skin Care")]
        public string DefaultModuleName {
            get {
                return ((string)(this["DefaultModuleName"]));
            }
            set {
                this["DefaultModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastEndDate {
            get {
                return ((global::System.DateTime)(this["LastEndDate"]));
            }
            set {
                this["LastEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastStartDate {
            get {
                return ((global::System.DateTime)(this["LastStartDate"]));
            }
            set {
                this["LastStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LossCompassDefaultView {
            get {
                return ((int)(this["LossCompassDefaultView"]));
            }
            set {
                this["LossCompassDefaultView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LossCompassState {
            get {
                return ((int)(this["LossCompassState"]));
            }
            set {
                this["LossCompassState"] = value;
            }
        }
    }
}
